import { ProgrammingProps } from "../../components/sections/Programming/types";

import onovolav from "../images/organizationLogo/onovolab.svg";
import amdocs from "../images/organizationLogo/amdocs.svg";
import csd from "../images/organizationLogo/CsdLogo.svg";
import dio from "../images/organizationLogo/DIO.svg";
import softable from "../images/organizationLogo/SoftableLogo.svg";
import StepWise from "../images/lecturers/StepWise.svg";
import GabrielZutiao from "../images/lecturers/GabrielZutiao.svg";
import CarlaoPereira from "../images/lecturers/CarlaoPereira.svg";
import LauraLuchiari from "../images/lecturers/LauraLuchiari.svg";
import LeonardoCerminaro from "../images/lecturers/LC.svg";
import kakautech from "../images/KakauTech.svg";
import Pet from "../images/PET.svg";
import DP_LC from "../images/lecturers/DP_LC.svg";
import FG_LA from "../images/lecturers/FG_LA.svg";
import JeanValdevino from "../images/lecturers/JeanValdevino.svg";
import TiagoTamega from "../images/lecturers/TiagoTamega.svg";

export const programmingContent: ProgrammingProps[] = [
  {
    name: "Abertura VI WECOMP",
    image: onovolav,
    imageDescription: "OnovoLab",
    bio: "",
    author: "",
    date: "03 de Outubro",
    time: "19h00 - 22h00",
    link: "https://www.sympla.com.br/evento/abertura-da-vi-semana-da-computacao-wecomp-do-ifsp-sao-carlos/3118603",
    vacancies: 300,
    location: "ONOVOLAB",
    description:
      "A abertura oficial da VI Wecomp acontecerá no ONOVOLAB e contará com a presença de empresas parceiras, uma mesa redonda com o tema 'Dev 2030: Como deverá ser a carreira de tech daqui a cinco anos?' e uma confraternização. Não perca!",
    typeEvent: "Opening",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "Da Ideia à Solução: Caminhos Reais na Entrega e Suporte de Tecnologia",
    image: amdocs,
    imageDescription:
      "Henrique Trimidi, Giovana Garcia, Ricardo Ortega e Misia Meyknecht",
    bio: "Henrique Trimidi: Domain Solution Expert; Com 12 anos de experiência na Amdocs, Henrique construiu uma carreira sólida na indústria de telecomunicações, atuando desde Desenvolvedor Júnior até Gerente de Desenvolvimento. Ex-aluno do IFSP, ele é especialista em soluções tecnológicas, com profundo conhecimento em desenvolvimento de software e uma visão estratégica voltada para inovação e eficiência em projetos complexos. \n Giovana Garcia: SW Developer; Graduanda em Análise e Desenvolvimento de Sistemas em São Carlos, iniciou sua trajetória acadêmica na UFSCar, na área de Ciências Sociais. Com o tempo, sua afinidade com tecnologia a levou a migrar para Análise e Desenvolvimento de Sistemas, onde vem se desenvolvendo como profissional da área. Recentemente contratada pela Amdocs, ela dá início à sua jornada no desenvolvimento de software; \n Ricardo Ortega: Site Lead; Com 33 anos de trajetória na área de Tecnologia da Informação, Ricardo acumula 27 anos de atuação como executivo em empresas nacionais e multinacionais, como Amdocs do Brasil, Elevadores Otis e Cromos Tintas Gráficas. Especialista em telecomunicações, possui sólida experiência em todo o ciclo de vida de projetos e suporte a sistemas, contribuindo diretamente para a entrega de soluções eficientes e sustentáveis para diversos clientes; \n Misia Meyknecht: TA Team Lead; Com 15 anos de experiência em recrutamento e seleção, atuou em empresas dos setores de marketing, tecnologia (software) e financeiro. Há 8 anos na Amdocs, onde lidera iniciativas estratégicas de aquisição de talentos para América Latina, com foco em atrair perfis alinhados à cultura organizacional e às necessidades do negócio.",
    author:
      "Henrique Trimidi, Giovana Garcia, Ricardo Ortega e Misia Meyknecht",
    date: "06 de Outubro",
    time: "19h00 - 21h00",
    link: "https://forms.gle/cFAUZW2VbzK5ZzGZA",
    vacancies: 110,
    location: "IFSP - C103",
    description:
      "Esta sessão interativa reúne profissionais de diferentes áreas para compartilhar suas trajetórias e experiências na entrega de soluções, suporte a sistemas e interação com usuários. O painel abordará como uma ideia nasce a partir da necessidade do cliente, os passos até sua implementação técnica e o papel essencial das áreas de suporte e operações.",
    typeEvent: "Talk",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "Conheça a CSD BR: Como a inovação tecnológica propiciou melhor desempenho e robustez para a nova clearing do Brasil",
    image: csd,
    imageDescription: "Equipe CSD BR",
    bio: "Guilherme Conrado é mestre em Engenharia Civil pela Escola Politécnica da USP e atua como Diretor de Fiscalização e Supervisão na CSD BR. Com mais de 20 anos de experiência, já liderou áreas de governança, riscos e controles internos, além de ter sido COO na LUZ Soluções Financeiras. Sua trajetória combina visão estratégica, capacidade analítica e sólida atuação em ambientes regulatórios e financeiros.",
    author: "Equipe CSD BR",
    date: "07 de Outubro",
    time: "19h00 - 21h00",
    link: "https://forms.gle/uEzNsrVoGk3ZRMmB7",
    vacancies: 110,
    location: "IFSP - C103",
    description:
      "Nessa talk, os profissionais da CSD BR apresentarão a empresa, a cultura, os desafios e as oportunidades disponíveis aos profissionais da região",
    typeEvent: "Talk",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "A Solução Começa na Orelha",
    image: kakautech,
    imageDescription: "Paulo Pedroso",
    bio: "Paulo Pedroso é pai do Pedro Henrique e do João Guilherme, e essa é a informação mais importante que precisam saber sobre ele. Sócio-fundador, atua como CTO na Kakau Tech desde 2022. Com mais de 30 anos no mercado, é apaixonado por tecnologia. Ele também é um músico muito talentoso, segundo ele mesmo e mais ninguém...",
    author: "Paulo Pedroso",
    date: "08 de Outubro",
    time: "19h00 - 21h00",
    link: "https://forms.gle/RZGhr6hM6bt3FT5V6",
    vacancies: 110,
    location: "IFSP - C103",
    description:
      "Esta palestra apresenta a Kakau Tech, uma empresa especializada em integrar a tecnologia digital aos negócios. Na Kakau Tech, o foco está em compreender profundamente os desafios dos clientes para oferecer soluções realmente relevantes. Este bate-papo busca mostrar que a tecnologia deve servir ao propósito de resolver problemas reais, e que o sucesso está em propor soluções simples e eficazes – em vez de apostar em ferramentas sofisticadas que não se conectam com as necessidades do cliente. Os participantes perceberão que a escuta ativa, aliada à identificação de oportunidades e à definição de estratégias de inovação, agrega valor prático, com exemplos do cotidiano empresarial e experiências do mercado.",
    typeEvent: "Talk",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "IA e Carreiras do Futuro: Tendências, Habilidades e Oportunidades",
    image: dio,
    imageDescription: "Venilton Falvo Jr ",
    bio: "Doutor em Engenharia de Software pelo ICMC-USP, com 16+ anos de experiência em soluções Web, Mobile e Cloud. Education Tech Lead na DIO, integra IA e metodologias inovadoras para ampliar a empregabilidade na comunidade tech. Possui certificações Microsoft, Oracle, Google e AWS, pesquisa o uso de IA na educação e atua como consultor em projetos estratégicos de arquitetura e alta performance.",
    author: "Venilton Falvo Jr ",
    date: "08 de Outubro",
    time: "21h00 - 22h00",
    link: "https://forms.gle/RZGhr6hM6bt3FT5V6",
    vacancies: 110,
    location: "IFSP - C103",
    description:
      "A IA está transformando o mercado de trabalho e abrindo novas possibilidades para profissionais de tecnologia. Neste talk da DIO, vamos explorar como a IA está transformando setores, redefinindo funções e criando oportunidades inéditas. Discutiremos as principais tendências que guiarão o futuro das carreiras, as habilidades mais valorizadas nesse novo cenário e como cada profissional pode se preparar para se destacar.",
    typeEvent: "Talk",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "Além do hype: criando uma empresa de tecnologia do zero",
    image: softable,
    imageDescription: "George Tamanaka e Gustavo Kobayashi",
    bio: "Há 8 anos, numa sala de apartamento, ainda na faculdade, George Tamanaka e Gustavo Kobayashi criaram a Softable, que tem a missão de devolver às empresas o controle sobre seus processos, oferecendo aos clientes soluções simples, acessíveis e transparentes que resolvem problemas reais.",
    author: "George Tamanaka e Gustavo Kobayashi",
    date: "09 de Outubro",
    time: "19h00 - 21h00",
    link: "https://forms.gle/NhDkEvw1tpBjGGSD8",
    vacancies: 110,
    location: "IFSP - C103",
    description:
      "Queremos te contar o que ninguém contou sobre empreender ainda na faculdade. Quais foram os desafios e aprendizados até a Softable se tornar parceira de tecnologia de algumas das maiores marcas do mundo.",
    typeEvent: "Talk",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "IA Generativa e Aplicações Reais em Projetos de Negócio.",
    image: StepWise,
    imageDescription: "StepWise",
    bio: "Lucas Albano formou-se em Engenharia da Computação pela USP São Carlos e atua como desenvolvedor de software, com experiência em front-end, back-end, integrações de sistemas, APIs e bancos de dados. Nos últimos anos, vem se dedicando à Inteligência Artificial Generativa, com projetos que envolvem implementações locais para maior privacidade e uso de APIs avançadas em aplicações complexas e multiagentes. Na StepWise, criou um assistente interno com diversas funcionalidades, incluindo visualização dinâmica de dados e adaptação de respostas com base em documentação proprietária; \n Guilherme Ichibara: Guilherme, Engenheiro de Computação pela USP São Carlos. Atua com back-end e engenharia de dados na Stepwise desde 2021, desenvolvendo APIs e integrações de sistemas internos, visando segurança dos dados. Entusiasta do uso de IA como assistente, mas prezando pela qualidade dos resultados; \n Michelangelo R. dos Anjos: Michelangelo é bacharel em Estatística pela UFSCar, mestrando em Ciência de Dados pela USP e também técnico em Informática. Atua há mais de 7 anos como coordenador de Data Science na Stepwise, onde lidera a área de Inovação no desenvolvimento de uma plataforma para automação de modelos estatísticos e definição de políticas  e regras de decisão. Além disso, conduz projetos de consultoria em ciência de dados, unindo experiência técnica e visão estratégica.",
    author: "Lucas Albano, Guilherme Ichibara, Michelangelo",
    date: "06 de Outubro",
    time: "08h00 - 11h30",
    link: "https://forms.gle/RPVdm52G1tdayzLSA",
    vacancies: 30,
    location: "IFSP - C106",
    description:
      "O minicurso tem como objetivo oferecer uma visão prática e objetiva sobre inteligência Artificial Generativa, abordando as técnicas existentes, os modelos utilizados e suas aplicações práticas em cases de negócio, utilizando infraestrutura offline e integrações com API's dos principais players do mercado. A partir de dois mini projetos, os participantes terão contato direto com exemplos reais de uso, conectando teoria e prática e demonstrando como essas soluções podem gerar valor em diferentes contextos de negócio.",
    typeEvent: "Course",
    classification: "Basic",
    status: "Closed",
  },
  {
    name: "Introdução à automação de testes com Playwright.",
    image: LeonardoCerminaro,
    imageDescription: "Leonardo Cerminaro",
    bio: "Leonardo é profissional de QA com sólida experiência em liderança de equipes e automação de testes. Atua em projetos internacionais, com foco em qualidade, processos ágeis e melhoria contínua há 7 anos, atualmente QA Lead na Riot Games.",
    author: "Leonardo Cerminaro",
    date: "06 de Outubro",
    time: "08h00 - 11h30",
    link: "https://forms.gle/PNTbEvqmFN9BH7qk6",
    vacancies: 20,
    location: "IFSP - C107",
    description:
      "Aprenda os fundamentos da automação de testes com Playwright em um minicurso prático, explorando conceitos, exemplos e primeiros scripts.",
    typeEvent: "Course",
    classification: "Basic",
    status: "Closed",
  },
  {
    name: "Desenvolvendo um aplicativo multiplataforma com Expo, Google Maps e Redux.",
    image: GabrielZutiao,
    imageDescription: "Gabriel Zutião",
    bio: "Gabriel Zutião é mestre em Ciência da Computação e Matemática Computacional pela USP e egresso do IFSP São Carlos. Com mais de seis anos de experiência na área, atua como desenvolvedor full-stack na Dimastec e possui experiência em React, React Native e Spring Boot, além de um grande interesse por sistemas operacionais alternativos.",
    author: "Gabriel Zutião",
    date: "06 de Outubro",
    time: "14h00 - 17h30",
    link: "https://forms.gle/ac64y7zHrzHrovkr8",
    vacancies: 30,
    location: "IFSP - C107",
    description:
      "Neste minicurso vamos explorar a utilização das bibliotecas react-native-maps e Redux em um aplicativo React Native gerenciado pela plataforma Expo. Faremos um app que acompanha o progresso de uma caminhada/trilha e mostra informações úteis para o usuário.",
    typeEvent: "Course",
    classification: "Intermediary",
    status: "Closed",
  },
  {
    name: "Por que 90% dos apps quebram em 6 meses — e como evitar isso com arquitetura e MVVM",
    image: FG_LA,
    imageDescription: "Francisco Galindo e Lucas Almeida",
    bio: "Francisco Galindo é ex-aluno do IFSP, formado em Análise e Desenvolvimento de Software. Em 2023, foi monitor de Algoritmos e Programação I & II, ajudando outros alunos a compreenderem as bases da lógica computacional. No ano seguinte, iniciou sua trajetória profissional como desenvolvedor mobile na Biotrônica, e em 2025 atuou como engenheiro de software na Softable. Atualmente, é Analista de Desenvolvimento Jr. na Tecnomotor.;\n Lucas Almeida, também ex-aluno do IFSP, trilhou o mesmo curso de Análise e Desenvolvimento de Software. Em 2023, integrou o PET/ADS, onde participou de projetos acadêmicos e atividades de pesquisa. Em 2024, ingressou na Biotrônica como desenvolvedor mobile, e hoje segue sua carreira como Engenheiro de Software I na Softable.",
    author: "Francisco Galindo e Lucas Almeida",
    date: "07 de Outubro",
    time: "08h00 - 11h30",
    link: "https://forms.gle/F9t5gK3ZR7UuFuMG8",
    vacancies: 30,
    location: "IFSP - C107",
    description:
      "A maioria dos apps falha porque o código apodrece rápido demais. Você começa empolgado, coloca tudo em uma Activity, e em semanas vira um caos. Isso não é azar, é falta de arquitetura. MVVM não é luxo: é disciplina, é o que separa um app descartável de um software profissional. Neste minicurso você vai aprender, na prática, a estruturar seu código para durar, ser testável e crescer sem colapsar. Esqueça atalhos: arquitetura é sobrevivência.",
    typeEvent: "Course",
    classification: "Intermediary",
    status: "Closed",
  },
  {
    name: "Introdução ao Clojure — explorando a programação funcional.",
    image: JeanValdevino,
    imageDescription: "Jean Valdevino",
    bio: "Jean Valdevino é engenheiro físico pela UFSCar e instrutor da Universidade Corporativa da CSD BR. Há três anos, ele forma devs com uma abordagem leve e direta, ensinando Clojure e outras tecnologias que estão mudando o jogo.",
    author: "Jean Valdevino",
    date: "07 de Outubro",
    time: "14h00 - 17h30",
    link: "https://forms.gle/79LxPviu4JR1UbMAA",
    vacancies: 30,
    location: "IFSP - C107",
    description:
      "Clojure é uma linguagem moderna, funcional e poderosa que vai te mostrar um novo jeito de programar — mais simples, mais expressivo e com foco em resultados. Durante o minicurso, você vai entender os fundamentos da programação funcional, conhecer a sintaxe do Clojure e criar um programa do zero, tudo de forma prática e descomplicada.",
    typeEvent: "Course",
    classification: "Intermediary",
    status: "Closed",
  },
  {
    name: "Git e GitHub: do mínimo que você precisa saber ao deploy no Vercel",
    image: Pet,
    imageDescription: "Lucas Oliveira",
    bio: "Lucas é um cientista da computação que se diverte projetando e desenvolvendo software há 20 anos. É professor do IFSP São Carlos desde 2015 e atual tutor do PET/ADS. Erick Santinon, Guilherme Mendes e Matheus Pacífico são alunos do curso de ADS do IFSP e bolsistas do grupo PET/ADS.",
    author: "Lucas Oliveira",
    date: "07 de Outubro",
    time: "14h00 - 17h30",
    link: "https://forms.gle/J1w4nmUEWu7rBJ91A",
    vacancies: 30,
    location: "IFSP - C106",
    description:
      "Neste minicurso, você aprenderá os conceitos básicos do Git, capacitando-o a usar essa ferramenta no dia a dia. Também será apresentada uma visão geral do GitHub e como integrá-lo ao Vercel para realizar deploys automáticos de páginas web.",
    typeEvent: "Course",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "Como sobreviver no terminal do Linux",
    image: CarlaoPereira,
    imageDescription: "Carlão Pereira",
    bio: "Carlão é professor efetivo do IFSP (campus São Carlos), desde 2012. Possui doutorado em Geografia pela UNESP, no qual desenvolveu um software para produção e análise de informações geográficas com o auxílio de técnicas de computação inteligente (lógica Nebulosa e redes neurais artificiais). É mestre pela Escola Nacional de Ciências Estatísticas e Tecnólogo em Processamento de Dados pela Universidade Veiga de Almeida. Usuário de Linux desde 2005, colaborador e disseminador da filosofia do Software Livre. Vascaíno sofredor.",
    author: "Carlão Pereira",
    date: "08 de Outubro",
    time: "08h00 - 11h30",
    link: "https://forms.gle/hjmqCXgGaKf8eGGk9",
    vacancies: 30,
    location: "IFSP - C107",
    description:
      "Este mini-curso apresentará uma breve história da filosofia do Software Livre e do surgimento do sistema operacional Linux, focando em seguida nos principais comandos para dominar o terminal e executar tarefas com agilidade e eficiência. Desde comandos básicos de navegação até operações mais avançadas, serão exploradas ferramentas essenciais para gestão de arquivos, instalação de programas, gerenciamento de processos, entre outros, de uma forma totalmente prática.",
    typeEvent: "Course",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "Desenvolvimento de Aplicações Híbridas com Capacitor",
    image: DP_LC,
    imageDescription: "Diego Pagotto e Luiz Chiquetano",
    bio: "Diego Pagotto é desenvolvedor P&D Júnior na Xmobots e atua com RTA, SpringBoot, React,  PostgreSQL,  Go e Python; \n Luiz Chiquetano é desenvolvedor P&D Júnior na Xmobots e trabalha com RTA, React, Typescript, Java e Kotlin. Ambos são egressos do curso de ADS do IFSP São Carlos. ",
    author: "Diego Pagotto e Luiz Chiquetano",
    date: "08 de Outubro",
    time: "14h00 - 17h30",
    link: "https://forms.gle/T8QyUSMd375RgkpQ6",
    vacancies: 30,
    location: "IFSP - C107",
    description:
      "Oficina prática sobre o desenvolvimento de aplicações híbridas utilizando Capacitor, explorando integração com frameworks web React, acesso a recursos nativos do dispositivo e empacotamento para Android. Serão abordados conceitos de configuração, plugins, ciclo de build e boas práticas para distribuição em lojas de aplicativos.",
    typeEvent: "Course",
    classification: "Intermediary",
    status: "Closed",
  },
  {
    name: "Programação Rústica: desbravando o Rust do zero",
    image: CarlaoPereira,
    imageDescription: "Carlão Pereira",
    bio: "Carlão é professor efetivo do IFSP (campus São Carlos), desde 2012. Possui doutorado em Geografia pela UNESP, no qual desenvolveu um software para produção e análise de informações geográficas com o auxílio de técnicas de computação inteligente (lógica Nebulosa e redes neurais artificiais). É mestre pela Escola Nacional de Ciências Estatísticas e Tecnólogo em Processamento de Dados pela Universidade Veiga de Almeida. Usuário de Linux desde 2005, colaborador e disseminador da filosofia do Software Livre. Vascaíno sofredor.",
    author: "Carlão Pereira",
    date: "09 de Outubro",
    time: "08h00 - 11h30",
    link: "https://forms.gle/BJQg1HrEQZya6kzU8",
    vacancies: 30,
    location: "IFSP - C107",
    description:
      "Rust é uma linguagem de programação moderna que vem ganhando destaque por unir alto desempenho, segurança de memória e um ecossistema em constante crescimento. Utilizada em grandes projetos de software e cada vez mais presente no mercado, ela se destaca como uma alternativa poderosa a linguagens tradicionais como C e C++. Nesta minicurso, vamos explorar os conceitos básicos da linguagem, entender sua proposta e dar os primeiros passos no desenvolvimento com Rust.",
    typeEvent: "Course",
    classification: "Basic",
    status: "Closed",
  },
  {
    name: "O Unicórnio da Tecnologia: Profissionais de TI que Sabem Vender",
    image: TiagoTamega,
    imageDescription: "Tiago Tâmega",
    bio: "Tiago Tâmega é gerente de tecnologia no Grupo ADN, com mais de 15 anos de experiência no setor de TI e ex-aluno do IFSP. Iniciou sua carreira na parte técnica, atuando como desenvolvedor e analista de qualidade, e ao longo do tempo transitou para funções de gestão, vendas e liderança. Já foi scrum master, gerente de projetos, CIO em empresa de soluções digitais e mentor de líderes. Também estruturou áreas de marketing e vendas e trabalhou diretamente com outsourcing de TI. É palestrante na Software Zen, além de participações nos eventos InterAgil, Inova Week e semanas da Tecnologia, compartilhando experiências sobre liderança, gestão ágil, transformação digital e o papel estratégico da tecnologia nos negócios.",
    author: "Tiago Tâmega",
    date: "09 de Outubro",
    time: "14h00 - 17h30",
    link: "https://forms.gle/YEq7T7TvyxUWu9Qq5",
    vacancies: 30,
    location: "IFSP - C106",
    description:
      "Você já percebeu que saber apenas programar ou configurar sistemas pode não garantir mais o seu futuro em tecnologia? As empresas estão em busca de um perfil raro: profissionais que entendem de tecnologia e sabem comunicar valor, gerar negócios e construir confiança. Neste encontro, vamos mostrar como transformar seu conhecimento técnico em vantagem competitiva, explorando caminhos de carreira que vão muito além da programação — e que podem ser altamente rentáveis. Se você quer se tornar o unicórnio que o mercado procura, esse é o seu lugar!",
    typeEvent: "Course",
    classification: "Free",
    status: "Closed",
  },
  {
    name: "Criando um chat de mensagens com React, TypeScript e WebSocket",
    image: LauraLuchiari,
    imageDescription: "Laura Luchiari",
    bio: "Laura Luchiari é uma desenvolvedora front-end formada em 2024 no curso de ADS pelo IFSP São Carlos. Além de gostar de estudar e implementar aplicações agradáveis e focadas na experiência do usuário, seus hobbies incluem desenhar, pintar, ler e jogar nas horas vagas.",
    author: "Laura Luchiari",
    date: "09 de Outubro",
    time: "14h00 - 17h30",
    link: "https://forms.gle/EiBXk7nm4z41ohD69",
    vacancies: 30,
    location: "IFSP - C107",
    description:
      "Neste minicurso, vamos desenvolver juntos uma aplicação de chat em tempo real usando React com TypeScript e WebSocket. O back-end já estará pronto, então o foco será na construção do front-end: implementação da interface, conexão e troca de mensagens entre usuários. Além disso, vamos abordar boas práticas de organização de código, assim como dicas e pontos importantes para quem deseja se aprimorar no desenvolvimento do dia a dia.",
    typeEvent: "Course",
    classification: "Intermediary",
    status: "Closed",
  },
];

export default programmingContent;